# Generated by Django 4.2.1 on 2023-06-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date_time', models.DateTimeField(verbose_name='Date & Time')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
    ]
