# Generated by Django 4.2.1 on 2023-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_event_attendees_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ManyToManyField(blank=True, to='main_app.event'),
        ),
    ]
