# Generated by Django 4.2.1 on 2023-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_attendee_event_attendee_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='secret_code',
            new_name='family_code',
        ),
    ]
