# Generated by Django 4.2.1 on 2023-06-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_attendee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='families',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.family'),
            preserve_default=False,
        ),
    ]
