# Generated by Django 4.2.1 on 2023-06-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_userprofile_families_userprofile_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.family'),
        ),
    ]
