# Generated by Django 4.2.2 on 2023-06-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.family'),
            preserve_default=False,
        ),
    ]
