# Generated by Django 4.2.2 on 2023-06-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_attendee_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='family',
        ),
    ]
