# Generated by Django 4.2.2 on 2023-06-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_event_date_alter_event_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
